# -*- coding: utf-8 -*-
"""ISSR_Hello_post_Flask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sa6VnjxM1GyGTE0x2j55wEgZdDbmhU7o
"""

!pip install flask --quiet
!pip install flask-ngrok --quiet
!pip install pyngrok==4.1.1

print("Completed!")

!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.tgz

!tar -xvf /content/ngrok-stable-linux-amd64.tgz

!./ngrok authtoken 2Y8NtSWYYomlGK1uHk0br1NgNT7_5QAnB9Bn8Mg5vhUA1iCbS

# import Flask from flask module
from flask import Flask, request, jsonify
import numpy as np


# import run_with_ngrok from flask_ngrok to run the app using ngrok
from flask_ngrok import run_with_ngrok

app = Flask(__name__) #app name
run_with_ngrok(app)
@app.after_request
def add_cors_headers(response):
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Headers'] = '*'
    response.headers['Content-Type'] = 'application/json'



    return response
@app.route('/', methods=['POST'])
def cosine_similarity_endpoint():
    # Parse request data
    data = request.get_json()
    print(data)
    # Return result as JSON
    return jsonify({'Hello': ' Ya '+data})

if __name__ == "__main__":
    app.run()

